In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn  as sns

In [ ]:
df = pd.read_csv('/content/healthcare_dataset.csv')
df

,Patient_ID,Gender,Age,Medical_Condition,Admission_Date,Admission_Type,Medical_Code,Billing_Amount,Discharge_Date
0,P1001,Male,45,Hypertension,15-01-2026,Urgent,ICD-10-I10,4500.0,20-01-2026
1,P1002,Female,32,Pneumonia,16-01-2026,Emergency,ICD-10-J18,6700.5,22-01-2026
2,P1003,Male,68,Diabetes Type 2,16-01-2026,Routine,ICD-10-E11,3200.0,18-01-2026
3,P1004,Female,55,Asthma,17-01-2026,Emergency,ICD-10-J45,5800.0,19-01-2026
4,P1005,Male,29,Fracture,17-01-2026,Urgent,ICD-10-S52,8500.0,25-01-2026
...,...,...,...,...,...,...,...,...,...
495,P1496,Female,50,COPD,20-09-2026,Emergency,ICD-10-J44,9800.0,23-09-2026
496,P1497,Male,28,Fracture,20-09-2026,Urgent,ICD-10-S52,9400.0,24-09-2026
497,P1498,Female,67,Heart Attack,21-09-2026,Emergency,ICD-10-I21,14200.0,25-09-2026
498,P1499,Male,43,Diabetes Type 2,21-09-2026,Routine,ICD-10-E11,4900.0,23-09-2026
499,P1500,Female,61,Stroke,22-09-2026,Emergency,ICD-10-I63,13900.0,26-09-2026

In [36]:
print("\nDataset Information:")
print(df.info())

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Patient_ID                 500 non-null    object
 1   Gender                     500 non-null    object
 2   Age                        500 non-null    int64
 3   Medical_Condition          500 non-null    object
 4   Admission_Date             500 non-null    datetime64[ns]
 5   Admission_Type             500 non-null    object
 6   Medical_Code               500 non-null    object
 7   Billing_Amount             500 non-null    float64
 8   Discharge_Date             500 non-null    datetime64[ns]
 9   Standardized_Medical_Code  500 non-null    object
 10  Hospital_Stay_Days         500 non-null    int64
dtypes: datetime64[ns](2), float64(1), int64(2), object(6)
memory usage: 43.1+ KB
None

In [41]:
print("\nMissing Values:")
print(df.isnull().sum())

Missing Values:
Patient_ID                   0
Gender                       0
Age                          0
Medical_Condition            0
Admission_Date               0
Admission_Type               0
Medical_Code                 0
Billing_Amount               0
Discharge_Date               0
Standardized_Medical_Code    0
Hospital_Stay_Days           0
dtype: int64

In [40]:
df['Medical_Code'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Name: Medical_Code, Length: 500, dtype: bool

In [19]:
df['Standardized_Medical_Code'] = df['Medical_Code'].str.replace('ICD-10-', '')
print(df[['Medical_Code', 'Standardized_Medical_Code']].head())

  Medical_Code Standardized_Medical_Code
0   ICD-10-I10                       I10
1   ICD-10-J18                       J18
2   ICD-10-E11                       E11
3   ICD-10-J45                       J45
4   ICD-10-S52                       S52

In [23]:
df['Admission_Date'] = pd.to_datetime(df['Admission_Date'], format='%d-%m-%Y')
df['Discharge_Date'] = pd.to_datetime(df['Discharge_Date'], format='%d-%m-%Y')

In [32]:
df['Hospital_Stay_Days'] = (df['Discharge_Date'] - df['Admission_Date']
).dt.days
print(df[['Admission_Date', 'Discharge_Date', 'Hospital_Stay_Days']].head())

  Admission_Date Discharge_Date  Hospital_Stay_Days
0     2026-01-15     2026-01-20                   5
1     2026-01-16     2026-01-22                   6
2     2026-01-16     2026-01-18                   2
3     2026-01-17     2026-01-19                   2
4     2026-01-17     2026-01-25                   8

In [29]:
print("Billing Amount:")
print(df['Billing_Amount'].describe())

Billing Amount:
count      500.00000
mean      7249.00100
std       3198.96932
min       2300.00000
25%       4400.00000
50%       6950.00000
75%       9400.00000
max      14200.00000
Name: Billing_Amount, dtype: float64

In [30]:
print("Hospital Stay Days:")
print(df['Hospital_Stay_Days'].describe())

Hospital Stay Days:
count    500.00000
mean       2.74400
std        1.17696
min        1.00000
25%        2.00000
50%        2.00000
75%        4.00000
max       10.00000
Name: Hospital_Stay_Days, dtype: float64

In [43]:
print("\nAverage Hospital Stay:")
print(df['Hospital_Stay_Days'].mean())

Average Hospital Stay:
2.744

In [27]:
print(df['Medical_Code'].value_counts())

Medical_Code
ICD-10-J44    34
ICD-10-K35    33
ICD-10-I63    33
ICD-10-J18    31
ICD-10-I50    30
ICD-10-N20    28
ICD-10-I10    28
ICD-10-I21    27
ICD-10-S52    22
ICD-10-K29    21
ICD-10-L03    20
ICD-10-M54    20
ICD-10-J45    19
ICD-10-G20    19
ICD-10-N39    18
ICD-10-O80    16
ICD-10-E11    16
ICD-10-T78    15
ICD-10-K80    15
ICD-10-E10    15
ICD-10-M81    12
ICD-10-M17    12
ICD-10-F41     9
ICD-10-G43     6
ICD-10-E03     1
Name: count, dtype: int64